### ISSUE TITLE
Cannot compile on PG 9.6 source installation because of pkg-config dependency

### ISSUE THREAD

**Issue by yazun** [moat/pmpp#7]
make
Package libpq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpq' found
ccache gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O3 -march=native -flto -fpic -fpic  -I. -I./ -I/home/postgres/pg96/include/server -I/home/postgres/pg96/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/distribute.o src/distribute.c
src/distribute.c:18:22: fatal error: libpq-fe.h: No such file or directory
 #include "libpq-fe.h"
                      ^
compilation terminated.
make: *** [src/distribute.o] Error 1

**Comment by coreyatmoat** [comment]
My guess is that your environment isn't set up for pg development. Assuming you're on an ubuntu system, you'd run
```
sudo apt-get install libpq-dev
```
See also http://stackoverflow.com/questions/13086073/rails-install-pg-cant-find-the-libpq-fe-h-header

**Comment by yazun** [comment]
It is setup for development but not dependent on any postgres packages as we compile the sources by ourselves, you can see we have a nonstandard blocksize:

pg_config
BINDIR = /home/postgres/pg96/bin
DOCDIR = /home/postgres/pg96/share/doc
HTMLDIR = /home/postgres/pg96/share/doc
INCLUDEDIR = /home/postgres/pg96/include
PKGINCLUDEDIR = /home/postgres/pg96/include
INCLUDEDIR-SERVER = /home/postgres/pg96/include/server
LIBDIR = /home/postgres/pg96/lib
PKGLIBDIR = /home/postgres/pg96/lib
LOCALEDIR = /home/postgres/pg96/share/locale
MANDIR = /home/postgres/pg96/share/man
SHAREDIR = /home/postgres/pg96/share
SYSCONFDIR = /home/postgres/pg96/etc
PGXS = /home/postgres/pg96/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-libxml' '--with-libxslt' '--prefix=/home/postgres/pg96' '--with-segsize=8' '--with-blocksize=16' '--with-wal-segsize=64' '--with-wal-blocksize=16' '--with-ldap' 'CC=ccache gcc' '--with-python' 'CFLAGS=-O3 -march=native -flto'
CC = ccache gcc
CPPFLAGS = -DFRONTEND -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O3 -march=native -flto
CFLAGS_SL = -fpic
LDFLAGS = -L../../src/common -Wl,--as-needed -Wl,-rpath,'/home/postgres/pg96/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lz -lreadline -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 9.6.0

**Comment by coreyatmoat** [comment]
Inability to find libpq in your development path is outside the scope of this project.

**Comment by yazun** [comment]
copied from previous comment: 

ls -lt $(pg_config --pkgincludedir)/libpq-fe.h
-rw-r--r-- 1 postgres postgres 21900 Nov 3 02:12 /home/postgres/pg96/include/libpq-fe.h

it's rather pmpp (which I like the idea of a lot) extension not following standard pg approach. 

cheers

**Comment by coreyatmoat** [comment]
It works with PGXN. If you wish to submit a pull request which also works with PGXN, I'll merge it.

**Comment by yazun** [comment]
thanks,  
removing all pkg-config references and adding

PG_CPPFLAGS= $(shell $(PG_CONFIG) --cflags ) -I $(shell $(PG_CONFIG) --includedir)

in Makefile worked.

cheers

**Comment by coreyatmoat** [comment]
Can you submit a pull request?
